### ISSUE TITLE
The method setNode(String) is undefined for the type EntityCapabilitiesManager

### ISSUE THREAD

**Issue by vitalyster** [sco0ter/babbler#173]
Broken in 0.9

**Comment by sco0ter** [comment]
Yes, sorry, it moved to ```ClientEntityCapabilities1Protocol```, because I abstracted [XEP-115](https://xmpp.org/extensions/xep-0115.html) and [XEP-390](https://xmpp.org/extensions/xep-0390.html).

```EntityCapabilitiesManager``` is now an interface which manages both protocols (the implementation of it, ```ClientEntityCapabilitiesManager```).

Because you cannot set a 'node' in XEP-390 (it is computed), the ```setNode``` got removed.

Try this:

```xmppClient.getManager(ClientEntityCapabilities1Protocol.class).setNode("mynode");```

**Comment by vitalyster** [comment]
Yes, works as expected, thanks

**Comment by sco0ter** [comment]
You are fast ;-)
