### ISSUE TITLE
File transfers are not available since 0.9

### ISSUE THREAD

**Issue by vitalyster** [sco0ter/babbler#178]
I receive `service-unavailable` error just like IQ handler is not set. `FileTransferManager` is configured like in 0.8. Added `setEnabled(true)` but that does not help too. Something missing?

**Comment by sco0ter** [comment]
Oh, I am sorry for that. I disabled [XEP-0096: SI File Transfer](https://xmpp.org/extensions/xep-0096.html) by default in 0.9 because it got deprecated by the XSF. (Unfortunately, the recommended alternative, [XEP-0234: Jingle File Transfer](https://xmpp.org/extensions/xep-0234.html) is in status "Deferred" and also not implemented in this library).

Please try:
```
xmppSession.enableFeature(StreamInitiation.NAMESPACE);
```

**Comment by vitalyster** [comment]
Thanks, now it works as usual.
